my_template/my_app/urls.py
from django.urls import path
from my_app import views

#template tagging
app_name = 'my_ap'

urlpatterns = [
    path('relative/', views.relative, name = 'relative'),
    path('other/',views.other, name = 'other'),
]

my_template/my_template/urls.py
from django.contrib import admin
from django.urls import path, include
from my_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls'))
]

my_template/my_app/models.py
from django.db import models

# Create your models here.

my_template/my_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict= {'text':'hello world', 'number':100}
    return render(request, 'my_app/index.html', context_dict)

def other(request):
    return render(request, 'my_app/other.html')

def relative(request):
    return render(request, 'my_app/relative.html')

my_template/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li class="navbar-brand"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="navbar-brand"><a class="navbar-link" href="{% url 'my_ap:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}


      {% endblock %}

    </div>
  </body>
</html>

my_template/templates/my_app/index.html
<!DOCTYPE html>
{% extends "my_app/base.html" %}
  {% block body_block %}
{% load my_extras %}

    <h1>WELCOME TO INDEX</h1>
    <h2>This is INDEX.html</h2>
    <h1>{{text|cuttt:'world' }}</h1>
    <h2>{{number|add:"99"}}</h2>

  {% endblock %}

my_template/templates/my_app/other.html
<!DOCTYPE html>
{% extends "my_app/base.html "%}
  {% block body_block %}
        <h1>Welcom to  OTHER!</h1>
        <h2>THis is an example of template inhereted</h2>
  {% endblock %}

my_template/templates/my_app/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcom to RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'my_ap:other' %}">MY LIFE!</a> <br>
    <a href="{% url 'admin:index'%}">Go to ADMIN page</a> <br>
    <a href="{% url 'index' %}">INDEX</a>

  </body>
</html>